# Generated by Django 2.2.7 on 2019-11-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
