# Generated by Django 2.2.7 on 2019-11-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
