# Generated by Django 2.2.7 on 2019-11-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='file',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
