# Generated by Django 2.2.7 on 2019-11-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_clothing_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothing',
            old_name='file',
            new_name='image',
        ),
    ]
