# Generated by Django 2.2.7 on 2019-11-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20191122_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
