# Generated by Django 2.2.7 on 2019-11-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_auto_20191122_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='itemid',
            field=models.TextField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
