# Generated by Django 2.2.7 on 2019-11-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_auto_20191125_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='desc',
            field=models.TextField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
