# Generated by Django 2.2.7 on 2019-11-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_brand_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='desc',
            field=models.TextField(max_length=400),
        ),
    ]
