# Generated by Django 2.2.7 on 2019-11-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_auto_20191125_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='desc',
            field=models.TextField(max_length=800),
        ),
    ]
