# Generated by Django 2.2.7 on 2019-11-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='keywords',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
